export const GOLOMT_MERCHANT_REGENERATION_COUNT = 5;
export const GOLOMT_MERCHANT_EXPIRY_TIME = 600000;
export const GOLOMT_MERCHANT_SECRET = process.env.MOTFOREX_GOLOMT_MERCHANT_SECRET;
export const GOLOMT_MERCHANT_TOKEN = process.env.MOTFOREX_GOLOMT_MERCHANT_TOKEN;
