export const COMMISSION_TYPE_ADDITIONAL = 'ADDITIONAL';
export const COMMISSION_TYPE_INCLUDED = 'INCLUDED';
export const COMMISSION_TYPE_PERCENT = 'PERCENT';
export const COMMISSION_TYPE_FIXED = 'FIXED';
