export const COMMISSION_TYPE_PERCENT = 'PERCENT';
export const COMMISSION_TYPE_FIXED = 'FIXED';

export const STATUS_INITIAL = 'INITIAL';
export const STATUS_PENDING = 'PENDING';
export const STATUS_CANCELLED = 'CANCELLED';
export const STATUS_EXPIRED = 'EXPIRED';
export const STATUS_PROCESSING = 'PROCESSING';
export const STATUS_PAYOUT = 'PAYOUT';
export const STATUS_HALTED = 'HALTED';
export const STATUS_FAILED = 'FAILED';
export const STATUS_EXECUTED = 'EXECUTED';
export const STATUS_REJECTED = 'REJECTED';
